version: "2"

linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pavel-snyk/snyk-sdk-go

output:
  formats:
    tab:
      path: stdout
      colors: false
